import type { CSSProperties } from 'react';
import type {
  ComponentContentMap,
  ComponentSize,
  ComponentSpec,
  ComponentType,
  ComponentVariant,
} from '@/types/components';
import { COMPONENT_SIZES, COMPONENT_VARIANTS } from '@/types/components';
import type { ExportFile } from '@/types/export';
import type { ComponentStyleDef } from '@/engine/componentRenderer';
import { STYLE_DICTIONARY } from '@/engine/componentRenderer';
import { nestedButtonStyles } from '@/components/library/_shared';
import { DEFAULT_CONTENT } from '@/components/library/content';
import type { ExportSnapshot } from '@/engine/export/snapshot';
import { pascal, typesPresent } from '@/engine/export/snapshot';

/**
 * D-171. One `<PascalCase>.tsx` per component type present, with styles precomputed from the
 * style dictionary at export time — the exported code has no dependency on the studio's engine
 * and reads as plain React. Markup is Turn 3's, with `spec.content.x` replaced by props and every
 * `data-*` attribute retained so the exported `library.css` rules still apply.
 */

const syntheticSpec = <K extends ComponentType>(
  type: K,
  variant: ComponentVariant,
  size: ComponentSize,
  content: ComponentContentMap[K],
): ComponentSpec<K> => ({
  id: 'export',
  type,
  variant,
  size,
  content,
  pageId: null,
  sectionId: null,
  createdBy: 'human',
  createdAt: 0,
});

/** All 15 variant × size combinations for one content shape. */
function styleTable(type: ComponentType, content: ComponentContentMap[ComponentType]): string {
  const def = STYLE_DICTIONARY[type] as ComponentStyleDef;
  const table: Record<string, Record<string, Record<string, CSSProperties>>> = {};
  for (const variant of COMPONENT_VARIANTS) {
    table[variant] = {};
    for (const size of COMPONENT_SIZES)
      table[variant]![size] = def.styles(syntheticSpec(type, variant, size, content) as ComponentSpec);
  }
  return JSON.stringify(table, null, 2);
}

/**
 * Derived from what `styles()` actually returns, not from the declared `parts` list: a few
 * dictionary entries spread a shared builder and produce one part more than they declare
 * (`select` inherits `helper` from the input decls). The emitted type has to match the emitted
 * object, or the exported file will not compile.
 */
const partsUnion = (type: ComponentType, content: ComponentContentMap[ComponentType]): string => {
  const def = STYLE_DICTIONARY[type] as ComponentStyleDef;
  return Object.keys(def.styles(syntheticSpec(type, 'primary', 'md', content) as ComponentSpec))
    .map((p) => `'${p}'`)
    .join(' | ');
};

const lit = (v: unknown): string => JSON.stringify(v);

const HEADER = (name: string, product: string) => `/**
 * ${name} — generated by Alternative Galaxy for ${product}.
 *
 * Styles are precomputed from the design tokens; every value resolves to a CSS custom property
 * declared in tokens.css. Load tokens.css once (it also carries the interactive-state rules) and
 * put \`container: canvas / inline-size\` on your page root so the responsive rules apply.
 */
'use client';`;

const PRELUDE = `
type Decl = CSSProperties & Record<string, string | number>;
export type Variant = 'primary' | 'secondary' | 'ghost' | 'danger' | 'outline';
export type Size = 'sm' | 'md' | 'lg';
`;

interface Built {
  imports: string;
  extraConst: string;
  props: string;
  signature: string;
  body: string;
}

type Content<K extends ComponentType> = ComponentContentMap[K];

const D = DEFAULT_CONTENT;

/** Per-type props + JSX. Keys mirror `ComponentType`. */
const BUILDERS: { [K in ComponentType]: () => Built } = {
  button: () => ({
    imports: '',
    extraConst: '',
    props: `  label?: string;
  onClick?: () => void;
  disabled?: boolean;
  loading?: boolean;`,
    signature: `{ variant = 'primary', size = 'md', label = ${lit(D.button.label)}, onClick, disabled, loading }: ButtonProps`,
    body: `  const s = STYLES[variant][size];
  return (
    <button
      type="button"
      data-alt="button"
      data-variant={variant}
      data-size={size}
      data-state={disabled ? 'disabled' : loading ? 'loading' : 'default'}
      data-part="root"
      style={s.root}
      onClick={onClick}
      disabled={disabled || loading}
    >
      {label}
    </button>
  );`,
  }),

  card: () => ({
    imports: '',
    extraConst: `const NESTED_BUTTON: Record<Variant, Decl> = ${JSON.stringify(
      Object.fromEntries(COMPONENT_VARIANTS.map((v) => [v, nestedButtonStyles(v, 'sm')])),
      null,
      2,
    )};
`,
    props: `  title?: string;
  body?: string;
  ctaLabel?: string | null;`,
    signature: `{ variant = 'primary', size = 'md', title = ${lit(D.card.title)}, body = ${lit(D.card.body)}, ctaLabel = ${lit(D.card.ctaLabel)} }: CardProps`,
    body: `  const s = STYLES[variant][size];
  const id = useId();
  return (
    <article
      data-alt="card"
      data-variant={variant}
      data-size={size}
      data-state="default"
      data-part="root"
      aria-labelledby={id}
      style={s.root}
    >
      <h3 id={id} data-part="title" style={s.title}>
        {title}
      </h3>
      <p data-part="body" style={s.body}>
        {body}
      </p>
      {ctaLabel && (
        <div data-part="actions" style={s.actions}>
          <button
            type="button"
            data-alt="button"
            data-variant={variant}
            data-size="sm"
            data-state="default"
            style={NESTED_BUTTON[variant]}
          >
            {ctaLabel}
          </button>
        </div>
      )}
    </article>
  );`,
  }),

  input: () => field('input'),
  textarea: () => field('textarea'),

  select: () => ({
    imports: '',
    extraConst: '',
    props: `  label?: string;
  placeholder?: string;
  options?: string[];
  value?: string;
  onChange?: ChangeEventHandler<HTMLSelectElement>;
  disabled?: boolean;`,
    signature: `{ variant = 'primary', size = 'md', label = ${lit(D.select.label)}, placeholder = ${lit(D.select.placeholder)}, options = ${lit(D.select.options)}, value, onChange, disabled }: SelectProps`,
    body: `  const s = STYLES[variant][size];
  const id = useId();
  return (
    <div data-alt="select" data-variant={variant} data-size={size} data-state={disabled ? 'disabled' : 'default'} data-part="root" style={s.root}>
      <label htmlFor={id} data-part="label" style={s.label}>
        {label}
      </label>
      <select id={id} value={value} onChange={onChange} disabled={disabled} data-part="field" style={s.field}>
        <option value="" disabled>
          {placeholder}
        </option>
        {options.map((o) => (
          <option key={o} value={o}>
            {o}
          </option>
        ))}
      </select>
      <svg data-part="chevron" style={s.chevron} viewBox="0 0 16 16" aria-hidden="true">
        <path d="M4 6l4 4 4-4" fill="none" stroke="currentColor" strokeWidth="1.5" />
      </svg>
    </div>
  );`,
  }),

  toggle: () => ({
    imports: '',
    extraConst: `const STYLES_ON: Record<Variant, Record<Size, Record<Part, Decl>>> = ${styleTable('toggle', {
      ...D.toggle,
      checked: true,
    })};
`,
    props: `  label?: string;
  checked?: boolean;
  onChange?: (checked: boolean) => void;
  disabled?: boolean;`,
    signature: `{ variant = 'primary', size = 'md', label = ${lit(D.toggle.label)}, checked = false, onChange, disabled }: ToggleProps`,
    body: `  const s = STYLES[variant][size];
  const on = STYLES_ON[variant][size];
  const id = useId();
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      aria-labelledby={id}
      disabled={disabled}
      onClick={() => onChange?.(!checked)}
      data-alt="toggle"
      data-variant={variant}
      data-size={size}
      data-state={disabled ? 'disabled' : 'default'}
      data-part="root"
      style={{ ...s.root, background: 'none', border: 'none', padding: 0 }}
    >
      <span data-part="track" style={checked ? on.track : s.track}>
        <span data-part="thumb" style={checked ? on.thumb : s.thumb} />
      </span>
      <span id={id} data-part="label" style={s.label}>
        {label}
      </span>
    </button>
  );`,
  }),

  badge: () => ({
    imports: '',
    extraConst: '',
    props: `  label?: string;`,
    signature: `{ variant = 'primary', size = 'md', label = ${lit(D.badge.label)} }: BadgeProps`,
    body: `  const s = STYLES[variant][size];
  return (
    <span data-alt="badge" data-variant={variant} data-size={size} data-state="default" data-part="root" style={s.root}>
      {label}
    </span>
  );`,
  }),

  avatar: () => ({
    imports: '',
    extraConst: '',
    props: `  initials?: string;
  name?: string;`,
    signature: `{ variant = 'primary', size = 'md', initials = ${lit(D.avatar.initials)}, name = ${lit(D.avatar.name)} }: AvatarProps`,
    body: `  const s = STYLES[variant][size];
  return (
    <span
      role="img"
      aria-label={name}
      title={name}
      data-alt="avatar"
      data-variant={variant}
      data-size={size}
      data-state="default"
      data-part="root"
      style={s.root}
    >
      {initials}
    </span>
  );`,
  }),

  navbar: () => ({
    imports: '',
    extraConst: '',
    props: `  brand?: string;
  links?: string[];
  ctaLabel?: string;`,
    signature: `{ variant = 'primary', size = 'md', brand = ${lit(D.navbar.brand)}, links = ${lit(D.navbar.links)}, ctaLabel = ${lit(D.navbar.ctaLabel)} }: NavbarProps`,
    body: `  const s = STYLES[variant][size];
  return (
    <nav aria-label="Primary" data-alt="navbar" data-variant={variant} data-size={size} data-state="default" data-part="root" style={s.root}>
      <a href="#" data-part="brand" style={s.brand}>
        {brand}
      </a>
      <ul data-part="links" style={s.links}>
        {links.map((l) => (
          <li key={l}>
            <a href="#" data-part="link" style={s.link}>
              {l}
            </a>
          </li>
        ))}
      </ul>
      <button
        type="button"
        data-part="menu"
        aria-label="Open menu"
        style={{ ...s.cta, backgroundColor: 'transparent', color: 'var(--color-text-primary)', borderColor: 'var(--color-border)' }}
      >
        <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true">
          <path d="M2 4h12M2 8h12M2 12h12" stroke="currentColor" strokeWidth="1.5" />
        </svg>
      </button>
      <button type="button" data-part="cta" style={s.cta}>
        {ctaLabel}
      </button>
    </nav>
  );`,
  }),

  hero: () => ({
    imports: '',
    extraConst: '',
    props: `  headline?: string;
  subtitle?: string;
  primaryCta?: string;
  secondaryCta?: string | null;`,
    signature: `{ variant = 'primary', size = 'md', headline = ${lit(D.hero.headline)}, subtitle = ${lit(D.hero.subtitle)}, primaryCta = ${lit(D.hero.primaryCta)}, secondaryCta = ${lit(D.hero.secondaryCta)} }: HeroProps`,
    body: `  const s = STYLES[variant][size];
  const id = useId();
  return (
    <section aria-labelledby={id} data-alt="hero" data-variant={variant} data-size={size} data-state="default" data-part="root" style={s.root}>
      <h1 id={id} data-part="headline" style={s.headline}>
        {headline}
      </h1>
      <p data-part="subtitle" style={s.subtitle}>
        {subtitle}
      </p>
      <div data-part="actions" style={s.actions}>
        <button type="button" data-part="primaryCta" style={s.primaryCta}>
          {primaryCta}
        </button>
        {secondaryCta && (
          <button type="button" data-part="secondaryCta" style={s.secondaryCta}>
            {secondaryCta}
          </button>
        )}
      </div>
    </section>
  );`,
  }),

  'pricing-card': () => ({
    imports: '',
    extraConst: `const STYLES_FEATURED: Record<Variant, Record<Size, Record<Part, Decl>>> = ${styleTable(
      'pricing-card',
      {
        ...D['pricing-card'],
        featured: true,
      },
    )};
`,
    props: `  tier?: string;
  price?: string;
  period?: string;
  features?: string[];
  ctaLabel?: string;
  featured?: boolean;`,
    signature: `{ variant = 'primary', size = 'md', tier = ${lit(D['pricing-card'].tier)}, price = ${lit(D['pricing-card'].price)}, period = ${lit(D['pricing-card'].period)}, features = ${lit(D['pricing-card'].features)}, ctaLabel = ${lit(D['pricing-card'].ctaLabel)}, featured = false }: PricingCardProps`,
    body: `  const s = (featured ? STYLES_FEATURED : STYLES)[variant][size];
  const id = useId();
  return (
    <article
      aria-labelledby={id}
      data-alt="pricing-card"
      data-variant={variant}
      data-size={size}
      data-state="default"
      data-part="root"
      style={s.root}
    >
      {featured && <span data-part="featuredBadge">Most popular</span>}
      <p id={id} data-part="tier" style={s.tier}>
        {tier}
      </p>
      <p data-part="price" style={s.price}>
        {price}
      </p>
      <p data-part="period" style={s.period}>
        {period}
      </p>
      <ul data-part="features" style={s.features}>
        {features.map((f) => (
          <li key={f} data-part="feature" style={s.feature}>
            <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true" style={{ color: 'var(--color-success)', flexShrink: 0 }}>
              <path d="M3 8.5l3 3 7-7" fill="none" stroke="currentColor" strokeWidth="1.8" />
            </svg>
            {f}
          </li>
        ))}
      </ul>
      <button type="button" data-part="cta" style={s.cta}>
        {ctaLabel}
      </button>
    </article>
  );`,
  }),

  'feature-grid': () => ({
    imports: '',
    extraConst: '',
    props: `  items?: { title: string; body: string }[];
  columns?: 2 | 3 | 4;`,
    signature: `{ variant = 'primary', size = 'md', items = ${lit(D['feature-grid'].items)}, columns = ${lit(D['feature-grid'].columns)} }: FeatureGridProps`,
    body: `  const s = STYLES[variant][size];
  return (
    <section aria-label="Features" data-alt="feature-grid" data-variant={variant} data-size={size} data-state="default" data-part="root" style={s.root}>
      <ul data-part="grid" style={{ ...s.grid, gridTemplateColumns: \`repeat(\${columns}, minmax(0, 1fr))\` }}>
        {items.map((it, i) => (
          <li key={i} data-part="item" style={s.item}>
            <div data-part="icon" style={s.icon} aria-hidden="true">
              <svg width="20" height="20" viewBox="0 0 20 20">
                <circle cx="10" cy="10" r="6.5" fill="none" stroke="currentColor" strokeWidth="1.8" />
                <path d="M7 10l2 2 4-4" fill="none" stroke="currentColor" strokeWidth="1.8" />
              </svg>
            </div>
            <h3 data-part="title" style={s.title}>
              {it.title}
            </h3>
            <p data-part="body" style={s.body}>
              {it.body}
            </p>
          </li>
        ))}
      </ul>
    </section>
  );`,
  }),

  footer: () => ({
    imports: '',
    extraConst: '',
    props: `  brand?: string;
  columns?: { heading: string; links: string[] }[];
  copyright?: string;`,
    signature: `{ variant = 'primary', size = 'md', brand = ${lit(D.footer.brand)}, columns = ${lit(D.footer.columns)}, copyright = ${lit(D.footer.copyright)} }: FooterProps`,
    body: `  const s = STYLES[variant][size];
  return (
    <footer data-alt="footer" data-variant={variant} data-size={size} data-state="default" data-part="root" style={s.root}>
      <div data-part="top" style={s.top}>
        <p data-part="brand" style={s.brand}>
          {brand}
        </p>
        <div data-part="columns" style={s.columns}>
          {columns.map((col) => (
            <ul key={col.heading} data-part="column" style={s.column} aria-label={col.heading}>
              <li data-part="heading" style={s.heading}>
                {col.heading}
              </li>
              {col.links.map((l) => (
                <li key={l}>
                  <a href="#" data-part="link" style={s.link}>
                    {l}
                  </a>
                </li>
              ))}
            </ul>
          ))}
        </div>
      </div>
      <div data-part="bottom" style={s.bottom}>
        <p data-part="copyright" style={s.copyright}>
          {copyright}
        </p>
      </div>
    </footer>
  );`,
  }),

  modal: () => ({
    imports: `import { useEffect, useRef } from 'react';
import { createPortal } from 'react-dom';`,
    extraConst: '',
    props: `  title?: string;
  body?: string;
  confirmLabel?: string;
  cancelLabel?: string;
  open?: boolean;
  onClose?: () => void;
  onConfirm?: () => void;`,
    signature: `{ variant = 'primary', size = 'md', title = ${lit(D.modal.title)}, body = ${lit(D.modal.body)}, confirmLabel = ${lit(D.modal.confirmLabel)}, cancelLabel = ${lit(D.modal.cancelLabel)}, open = true, onClose, onConfirm }: ModalProps`,
    // D-103/D-171: the exported Modal adds a portal and a focus trap; the canvas version has neither.
    body: `  const s = STYLES[variant][size];
  const ref = useRef<HTMLDivElement>(null);
  const tId = useId();
  const bId = useId();

  useEffect(() => {
    if (!open) return;
    const previous = document.activeElement as HTMLElement | null;
    const items = () =>
      Array.from(
        ref.current?.querySelectorAll<HTMLElement>('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])') ?? [],
      );
    items()[0]?.focus();
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') return onClose?.();
      if (e.key !== 'Tab') return;
      const list = items();
      if (list.length === 0) return;
      const first = list[0]!;
      const last = list[list.length - 1]!;
      if (e.shiftKey && document.activeElement === first) {
        e.preventDefault();
        last.focus();
      } else if (!e.shiftKey && document.activeElement === last) {
        e.preventDefault();
        first.focus();
      }
    };
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('keydown', onKey);
      previous?.focus();
    };
  }, [open, onClose]);

  if (!open || typeof document === 'undefined') return null;

  return createPortal(
    <div
      data-alt="modal"
      data-variant={variant}
      data-size={size}
      data-state="default"
      data-part="root"
      style={{ ...s.root, position: 'fixed', inset: 0, minHeight: '100vh', zIndex: 1000 }}
    >
      <div data-part="backdrop" style={s.backdrop} aria-hidden="true" onClick={onClose} />
      <div ref={ref} role="dialog" aria-modal="true" aria-labelledby={tId} aria-describedby={bId} data-part="dialog" style={s.dialog}>
        <h2 id={tId} data-part="title" style={s.title}>
          {title}
        </h2>
        <p id={bId} data-part="body" style={s.body}>
          {body}
        </p>
        <div data-part="actions" style={s.actions}>
          <button type="button" data-part="cancel" style={s.cancel} onClick={onClose}>
            {cancelLabel}
          </button>
          <button type="button" data-part="confirm" style={s.confirm} onClick={onConfirm}>
            {confirmLabel}
          </button>
        </div>
      </div>
    </div>,
    document.body,
  );`,
  }),

  toast: () => ({
    imports: '',
    extraConst: '',
    props: `  message?: string;
  onDismiss?: () => void;`,
    signature: `{ variant = 'primary', size = 'md', message = ${lit(D.toast.message)}, onDismiss }: ToastProps`,
    body: `  const s = STYLES[variant][size];
  return (
    <div role="status" aria-live="polite" data-alt="toast" data-variant={variant} data-size={size} data-state="default" data-part="root" style={s.root}>
      <span data-part="bar" style={s.bar} aria-hidden="true" />
      <p data-part="message" style={s.message}>
        {message}
      </p>
      <button type="button" data-part="dismiss" aria-label="Dismiss" style={s.dismiss} onClick={onDismiss}>
        <svg width="14" height="14" viewBox="0 0 14 14" aria-hidden="true">
          <path d="M3 3l8 8M11 3l-8 8" stroke="currentColor" strokeWidth="1.5" />
        </svg>
      </button>
    </div>
  );`,
  }),

  accordion: () => ({
    imports: `import { useState } from 'react';`,
    extraConst: '',
    props: `  items?: { question: string; answer: string }[];`,
    signature: `{ variant = 'primary', size = 'md', items = ${lit(D.accordion.items)} }: AccordionProps`,
    body: `  const s = STYLES[variant][size];
  const id = useId();
  const [open, setOpen] = useState(0);
  return (
    <div data-alt="accordion" data-variant={variant} data-size={size} data-state="default" data-part="root" style={s.root}>
      {items.map((it, i) => {
        const tId = \`\${id}-t\${i}\`;
        const pId = \`\${id}-p\${i}\`;
        const isOpen = open === i;
        return (
          <div key={i} data-part="item" style={s.item}>
            <h3 style={{ margin: 0 }}>
              <button
                type="button"
                id={tId}
                aria-expanded={isOpen}
                aria-controls={pId}
                onClick={() => setOpen(isOpen ? -1 : i)}
                data-part="trigger"
                style={s.trigger}
              >
                <span data-part="question" style={s.question}>
                  {it.question}
                </span>
                <svg data-part="chevron" style={s.chevron} viewBox="0 0 16 16" aria-hidden="true">
                  <path d="M4 6l4 4 4-4" fill="none" stroke="currentColor" strokeWidth="1.5" />
                </svg>
              </button>
            </h3>
            <div id={pId} role="region" aria-labelledby={tId} hidden={!isOpen} data-part="panel" style={s.panel}>
              <p data-part="answer" style={s.answer}>
                {it.answer}
              </p>
            </div>
          </div>
        );
      })}
    </div>
  );`,
  }),
};

/** input and textarea share everything but the field element. */
function field(type: 'input' | 'textarea'): Built {
  const c = D[type] as Content<'input'>;
  const element =
    type === 'input'
      ? `      <input
        id={fieldId}
        type="text"
        placeholder={placeholder}
        value={value}
        onChange={onChange}
        disabled={disabled}
        aria-invalid={state === 'error' || undefined}
        aria-describedby={help ? helpId : undefined}
        data-part="field"
        style={s.field}
      />`
      : `      <textarea
        id={fieldId}
        rows={4}
        placeholder={placeholder}
        value={value}
        onChange={onChange}
        disabled={disabled}
        aria-invalid={state === 'error' || undefined}
        aria-describedby={help ? helpId : undefined}
        data-part="field"
        style={s.field}
      />`;
  const el = type === 'input' ? 'HTMLInputElement' : 'HTMLTextAreaElement';
  return {
    imports: '',
    extraConst: '',
    props: `  label?: string;
  placeholder?: string;
  helper?: string | null;
  error?: string | null;
  value?: string;
  onChange?: ChangeEventHandler<${el}>;
  disabled?: boolean;`,
    signature: `{ variant = 'primary', size = 'md', label = ${lit(c.label)}, placeholder = ${lit(c.placeholder)}, helper = ${lit(c.helper)}, error = ${lit(c.error)}, value, onChange, disabled }: ${pascal(type)}Props`,
    body: `  const s = STYLES[variant][size];
  const id = useId();
  const fieldId = \`\${id}-field\`;
  const helpId = \`\${id}-help\`;
  const state = error ? 'error' : disabled ? 'disabled' : 'default';
  const help = error ?? helper;
  return (
    <div data-alt="${type}" data-variant={variant} data-size={size} data-state={state} data-part="root" style={s.root}>
      <label htmlFor={fieldId} data-part="label" style={s.label}>
        {label}
      </label>
${element}
      {help && (
        <p id={helpId} data-part="helper" role={state === 'error' ? 'alert' : undefined} style={s.helper}>
          {help}
        </p>
      )}
    </div>
  );`,
  };
}

/** One component file. */
export function exportComponent(type: ComponentType, product: string): ExportFile {
  const name = pascal(type);
  const built = BUILDERS[type]();
  const needsUseId = /useId\(\)/.test(built.body);
  const needsChangeHandler = /ChangeEventHandler/.test(built.props);

  const reactNamed = [needsUseId ? 'useId' : null].filter(Boolean).join(', ');
  const reactTypes = ['CSSProperties', needsChangeHandler ? 'ChangeEventHandler' : null].filter(Boolean).join(', ');

  const contents = `${HEADER(name, product)}
${built.imports ? built.imports + '\n' : ''}${reactNamed ? `import { ${reactNamed} } from 'react';\n` : ''}import type { ${reactTypes} } from 'react';
${PRELUDE}
type Part = ${partsUnion(type, D[type])};

const STYLES: Record<Variant, Record<Size, Record<Part, Decl>>> = ${styleTable(type, D[type])};

${built.extraConst}
export interface ${name}Props {
  variant?: Variant;
  size?: Size;
${built.props}
}

export default function ${name}(${built.signature}) {
${built.body}
}
`;
  return { path: `components/${name}.tsx`, contents, language: 'tsx' };
}

/** Every component type present on the canvas or in a page (D-171). */
export function exportComponents(snap: ExportSnapshot): ExportFile[] {
  return typesPresent(snap)
    .sort()
    .map((type) => exportComponent(type, snap.productName));
}
